stages:
  extract_embeddings:
    cmd: python scripts/extract_embeddings.py --config configs/embedder.yaml
    deps:
    - configs/embedder.yaml
    - data/beauty/datamaps.json
    - data/beauty/meta.json.gz
    - scripts/extract_embeddings.py
    - src/embeddings_extraction
    outs:
    - outputs/beauty_minilm/embedding_stats.json
    - outputs/beauty_minilm/item_embeddings_l2norm.npy
    - outputs/beauty_minilm/item_embeddings_raw.npy
    - outputs/beauty_minilm/item_ids.json
    - outputs/beauty_minilm/item_text.json
  build_semantics:
    cmd: torchrun --rdzv-endpoint=localhost:1234 --nproc_per_node=2 scripts/build_semantics.py --config configs/quantizer.yaml
    deps:
    - configs/quantizer.yaml
    - outputs/beauty_minilm/embedding_stats.json
    - outputs/beauty_minilm/item_embeddings_raw.npy
    - outputs/beauty_minilm/item_ids.json
    - scripts/build_semantics.py
    - src/quantization
    outs:
    - outputs/beauty_rqkmeans/centroids_0.npy
    - outputs/beauty_rqkmeans/centroids_1.npy
    - outputs/beauty_rqkmeans/codes.npy
    - outputs/beauty_rqkmeans/codes_str.txt
    - outputs/beauty_rqkmeans/codes_str_with_suffix.txt
    - outputs/beauty_rqkmeans/codes_with_suffix.npy
    - outputs/beauty_rqkmeans/collision_suffix.npy
    - outputs/beauty_rqkmeans/rqkmeans_config.json
    - outputs/beauty_rqkmeans/summary.json
  train:
    cmd: torchrun --rdzv-endpoint=localhost:1234 --nproc_per_node=2 scripts/train_recommender.py --config configs/recommender.yaml
    deps:
    - configs/recommender.yaml
    - data/beauty/sequential_data.txt
    - outputs/beauty_minilm/item_ids.json
    - outputs/beauty_rqkmeans/codes_with_suffix.npy
    - scripts/train_recommender.py
    - src/generative_retrieval
    outs:
    - outputs/tiger_encdec
  evaluate:
    cmd: torchrun --rdzv-endpoint=localhost:1234 --nproc_per_node=2 scripts/test_recommender.py --config configs/recommender.yaml --model_dir outputs/tiger_encdec/checkpoint-final
    deps:
      - scripts/test_recommender.py
      - src/generative_retrieval
      - configs/recommender.yaml
      - data/beauty/sequential_data.txt
      - outputs/beauty_rqkmeans/codes_with_suffix.npy
      - outputs/beauty_minilm/item_ids.json
      - outputs/tiger_encdec
    metrics:
      - outputs/metrics/beauty_metrics.json:
          cache: false
